apiVersion: v1
entries:
  airports-frontend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-13T13:43:43.7613614+03:00"
    description: A Helm chart for Kubernetes
    digest: 7c56c46b7e17c933cbc506b3f4dbf9fcaf02080a1ccc0ea47b3b9b4eca206f32
    name: airports-frontend
    type: application
    urls:
    - airports-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2023-09-13T13:43:43.7604767+03:00"
